import { type Question } from '../types';

// Aquí configuras todo manualmente. Las imágenes deben estar en la carpeta public/problemas/
export const EXAM_QUESTIONS: Question[] = [
    {
        id: 'q1',
        imageUrl: '/problemas/1.png',
        options: ['A', 'B', 'C', 'D', 'E'],
        correctOptionIndex: 0,
    },
    {
        id: 'q2',
        imageUrl: '/problemas/2.png',
        options: ['A', 'B', 'C', 'D', 'E'],
        correctOptionIndex: 2,
    },
    {
        id: "q3",
        imageUrl: "/problemas/3.png",
        options: ['A', 'B', 'C', 'D', 'E'],
        correctOptionIndex: 2,
    },
    {
        id: "q4",
        imageUrl: "/problemas/4.png",
        options: ['A', 'B', 'C', 'D', 'E'],
        correctOptionIndex: 1,
    },
    {
        id: "q5",
        imageUrl: "/problemas/5.png",
        options: ['A', 'B', 'C', 'D', 'E'],
        correctOptionIndex: 2,
    },
    {
        id: "q6",
        imageUrl: "/problemas/6.png",
        options: ['A', 'B', 'C', 'D', 'E'],
        correctOptionIndex: 2,
    },
    {
        id: "q7",
        imageUrl: "/problemas/7.png",
        options: ['A', 'B', 'C', 'D', 'E'],
        correctOptionIndex: 1,
    },
    {
        id: "q8",
        imageUrl: "/problemas/8.png",
        options: ['A', 'B', 'C', 'D', 'E'],
        correctOptionIndex: 2,
    },
    {
        id: "q9",
        imageUrl: "/problemas/9.png",
        options: ['A', 'B', 'C', 'D', 'E'],
        correctOptionIndex: 4,
    },
    {
        id: "q10",
        imageUrl: "/problemas/10.png",
        options: ['A', 'B', 'C', 'D', 'E'],
        correctOptionIndex: 4,
    },
    {
        id: "q11",
        imageUrl: "/problemas/11.png",
        options: ['A', 'B', 'C', 'D', 'E'],
        correctOptionIndex: 0,
    },
    {
        id: "q12",
        imageUrl: "/problemas/12.png",
        options: ['A', 'B', 'C', 'D', 'E'],
        correctOptionIndex: 1,
    },
    {
        id: "q13",
        imageUrl: "/problemas/13.png",
        options: ['A', 'B', 'C', 'D', 'E'],
        correctOptionIndex: 2,
    },
    {
        id: "q14",
        imageUrl: "/problemas/14.png",
        options: ['A', 'B', 'C', 'D', 'E'],
        correctOptionIndex: 0,
    },
    {
        id: "q15",
        imageUrl: "/problemas/15.png",
        options: ['A', 'B', 'C', 'D', 'E'],
        correctOptionIndex: 4,
    },
    {
        id: "q16",
        imageUrl: "/problemas/16.png",
        options: ['A', 'B', 'C', 'D', 'E'],
        correctOptionIndex: 3,
    },
    {
        id: "q17",
        imageUrl: "/problemas/17.png",
        options: ['A', 'B', 'C', 'D', 'E'],
        correctOptionIndex: 0,
    },
    {
        id: "q18",
        imageUrl: "/problemas/18.png",
        options: ['A', 'B', 'C', 'D', 'E'],
        correctOptionIndex: 0,
    },
    {
        id: "q19",
        imageUrl: "/problemas/19.png",
        options: ['A', 'B', 'C', 'D', 'E'],
        correctOptionIndex: 2,
    },
    {
        id: "q20",
        imageUrl: "/problemas/20.png",
        options: ['A', 'B', 'C', 'D', 'E'],
        correctOptionIndex: 4,
    },
    {
        id: "q21",
        imageUrl: "/problemas/21.png",
        options: ['A', 'B', 'C', 'D', 'E'],
        correctOptionIndex: 4,
    },
    {
        id: "q22",
        imageUrl: "/problemas/22.png",
        options: ['A', 'B', 'C', 'D', 'E'],
        correctOptionIndex: 0,
    },
    {
        id: "q23",
        imageUrl: "/problemas/23.png",
        options: ['A', 'B', 'C', 'D', 'E'],
        correctOptionIndex: 0,
    },
    {
        id: "q24",
        imageUrl: "/problemas/24.png",
        options: ['A', 'B', 'C', 'D', 'E'],
        correctOptionIndex: 1,
    },
    {
        id: "q25",
        imageUrl: "/problemas/25.png",
        options: ['A', 'B', 'C', 'D', 'E'],
        correctOptionIndex: 2,
    },
    {
        id: "q26",
        imageUrl: "/problemas/26.png",
        options: ['A', 'B', 'C', 'D', 'E'],
        correctOptionIndex: 2,
    },
    {
        id: "q27",
        imageUrl: "/problemas/27.png",
        options: ['A', 'B', 'C', 'D', 'E'],
        correctOptionIndex: 2,
    },
    {
        id: "q28",
        imageUrl: "/problemas/28.png",
        options: ['A', 'B', 'C', 'D', 'E'],
        correctOptionIndex: 2,
    },
    {
        id: "q29",
        imageUrl: "/problemas/29.png",
        options: ['A', 'B', 'C', 'D', 'E'],
        correctOptionIndex: 1,
    },
    {
        id: "q30",
        imageUrl: "/problemas/30.png",
        options: ['A', 'B', 'C', 'D', 'E'],
        correctOptionIndex: 4,
    },
    // Agrega las demás preguntas aquí...
];